services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app/app
